<?php

/**
 * This file is part of the GZERO CMS package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Class AccountController
 *
 * @author     Adrian Skierniewski <adrian.skierniewski@gmail.com>
 * @copyright  Copyright (c) 2014, Adrian Skierniewski
 */
class AccountController extends BaseController {


    public function __construct()
    {
        // TODO: Create user links as filter
        App::make('user.menu')->addLink(URL::route('account'), 'user.my_account');
        App::make('user.menu')->addChild(['url' => URL::route('logout'), 'title' => 'common.logout'], URL::route('account'));


        // getting Menu links registered from other packages
        View::share('userMenu', App::make('user.menu')->getMenu());
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function account()
    {
        return View::make('account');
    }

    public function edit()
    {
        return View::make('account.edit');
    }
}
