<?php

use Gzero\Core\EntitySerializer;
use Gzero\Repository\ContentRepository;

class AdminContentApiController extends \BaseController {


    protected $contentRepo;
    protected $enSerializer;

    public function __construct(ContentRepository $contentRepository, EntitySerializer $entitySerializer)
    {
        $this->contentRepo  = $contentRepository;
        $this->enSerializer = $entitySerializer;
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $content = $this->contentRepo->getTranslationById($id);
        if (!empty($content)) {
            return Response::json(['success' => TRUE, 'data' => $this->enSerializer->toArray($content)]);
        }
        return Response::json(['success' => TRUE, 'data' => NULL]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function update($id)
    {
        $content = $this->contentRepo->getById($id);
        $this->contentRepo->update($content, Input::all());
        $this->contentRepo->commit();
        return Response::json(['success' => TRUE]);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $content = $this->contentRepo->getById($id);
        $this->contentRepo->delete($content);
        $this->contentRepo->commit();
        return Response::json(['success' => TRUE]);
    }
}
