<?php

use Gzero\Core\EntitySerializer;
use Gzero\Repository\ContentRepository;

class ContentApiController extends \BaseController {


    protected $contentRepo;
    protected $enSerializer;

    public function __construct(ContentRepository $contentRepository, EntitySerializer $entitySerializer)
    {
        $this->contentRepo  = $contentRepository;
        $this->enSerializer = $entitySerializer;
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $content = $this->contentRepo->getTranslationById($id);
        if (!empty($content)) {
            return Response::json(['success' => TRUE, 'data' => $this->enSerializer->toArray($content)]);
        }
        return Response::json(['success' => TRUE, 'data' => NULL]);
    }

    public function children($id)
    {
        $content = $this->contentRepo->getById($id);
        if (!empty($content)) {
            $list = $this->contentRepo->getChildren($content);
            $out  = [];
            foreach ($list as $value) {
                $out[] = $this->enSerializer->toArray($value);
            }
            return Response::json(['success' => TRUE, 'data' => $out]);
        }
        return Response::json(['success' => TRUE, 'data' => NULL]);
    }
}
